// ── FiF B Övn. 2 – Konjunktioner (välj bland tre alternativ) ─────────────────
export const FIB_KONJ = [
  {id:"k01",text:"Portiern frågade om vi ville ha två enkelrum ___ ett dubbelrum.",options:{A:"utan",B:"men",C:"eller"},correct:"C"},
  {id:"k02",text:"– Vad kan jag hjälpa till med? – Du kan antingen diska ___ torka.",options:{A:"så",B:"men",C:"eller"},correct:"C"},
  {id:"k03",text:"Åke ringde nyss från bilen och sa att han var på väg hem ___ att han skulle komma hem i tid.",options:{A:"och",B:"eller",C:"utan"},correct:"A"},
  {id:"k04",text:"Peter sa att han skulle köpa blommor ___ choklad till Lotta.",options:{A:"för",B:"så",C:"och"},correct:"C"},
  {id:"k05",text:"Uno undrade om jag ville sova över ___ om jag skulle åka hem.",options:{A:"och",B:"eller",C:"men"},correct:"B"},
  {id:"k06",text:"Elin går på kurs i engelska både på måndagar ___ på onsdagar.",options:{A:"men",B:"och",C:"eller"},correct:"B"},
  {id:"k07",text:"Mikaela vill antingen ha en kattunge ___ en hundvalp.",options:{A:"utan",B:"eller",C:"så"},correct:"B"},
  {id:"k08",text:"Mats har feber idag, ___ han är hemma från skolan.",options:{A:"för",B:"så",C:"men"},correct:"B"},
  {id:"k09",text:"– Vill du gå på bio ___ ska vi stanna hemma och ta det lugnt?",options:{A:"och",B:"men",C:"eller"},correct:"C"},
  {id:"k10",text:"Oskar vann fem miljoner på Lotto häromåret, ___ han fortsätter att jobba som vanligt.",options:{A:"så",B:"för",C:"men"},correct:"C"},
  {id:"k11",text:"Jag har inte ringt till Johan än, ___ jag ska göra det senare i kväll.",options:{A:"och",B:"eller",C:"men"},correct:"C"},
  {id:"k12",text:"Antingen Ester ___ Anders kommer på Torgnys fest.",options:{A:"och",B:"eller",C:"men"},correct:"B"},
  {id:"k13",text:"Janne sprang till bussen i morse, ___ han missade den i alla fall.",options:{A:"eller",B:"så",C:"men"},correct:"C"},
  {id:"k14",text:"Anita kan inte komma på lördag ___ tidigast på söndag.",options:{A:"så",B:"för",C:"utan"},correct:"C"},
  {id:"k15",text:"Tomas trivs inte på sitt jobb, ___ han försöker hitta ett annat.",options:{A:"för",B:"eller",C:"så"},correct:"C"},
  {id:"k16",text:"Visserligen är jag sen, ___ jag tror att jag hinner till tåget.",options:{A:"så",B:"eller",C:"men"},correct:"C"},
  {id:"k17",text:"Hjalmar gillar varken boxning ___ brottning.",options:{A:"och",B:"eller",C:"för"},correct:"B"},
  {id:"k18",text:"Jag ringde inte till Lena på födelsedagen, ___ jag åkte hem till henne och överraskade henne.",options:{A:"eller",B:"utan",C:"och"},correct:"B"},
  {id:"k19",text:"Niklas var hemma, ___ han var sjuk.",options:{A:"för",B:"så",C:"men"},correct:"A"},
];

// ── FiF B Övn. 5 – Subjunktioner (4 alternativ) ──────────────────────────────
export const FIB_SUBJ = [
  {id:"s01",text:"Polisen undrade ___ jag hade hört något om mordet förra veckan.",options:{A:"om",B:"att",C:"än",D:"som"},correct:"A"},
  {id:"s02",text:"Vi ska gå på teater på lördag ___ vi kan skaffa biljetter.",options:{A:"ifall",B:"som",C:"medan",D:"för att"},correct:"A"},
  {id:"s03",text:"Igår kväll stannade våra barn ute och lekte ända ___ det blev mörkt.",options:{A:"sedan",B:"medan",C:"tills",D:"när"},correct:"C"},
  {id:"s04",text:"– Polisen har gripit Lars ___ han har gjort något kriminellt.",options:{A:"om",B:"så att",C:"trots att",D:"utan att"},correct:"D"},
  {id:"s05",text:"Tom söker ett nytt arbete ___ han är uppsagd från sitt nuvarande jobb.",options:{A:"eftersom",B:"när",C:"att",D:"fastän"},correct:"A"},
  {id:"s06",text:"I lördags gick Patrik till jobbet ___ han var ledig.",options:{A:"genom att",B:"trots att",C:"utan att",D:"så att"},correct:"B"},
  {id:"s07",text:"Katarina bor i en likadan lägenhet ___ hennes mormor gör.",options:{A:"som",B:"än",C:"att",D:"fast"},correct:"A"},
  {id:"s08",text:"Det är så dimmigt ute idag ___ man nästan inte kan se något.",options:{A:"som",B:"att",C:"om",D:"trots att"},correct:"B"},
  {id:"s09",text:"Emma hänger tvätten ute ___ den ska lukta gott.",options:{A:"trots att",B:"för att",C:"genom att",D:"som"},correct:"B"},
  {id:"s10",text:"Doktor Ledman undrade ___ jag hade haft hosta länge.",options:{A:"om",B:"att",C:"som",D:"eftersom"},correct:"A"},
  {id:"s11",text:"– Det ser ut ___ du har feber.",options:{A:"som om",B:"ifall",C:"att",D:"trots att"},correct:"A"},
  {id:"s12",text:"___ jag inte är helt frisk i morgon ska jag gå till jobbet.",options:{A:"Även om",B:"Om",C:"Medan",D:"Eftersom"},correct:"A"},
  {id:"s13",text:"Man brukar renskriva sin uppsats ___ man lämnar in den till läraren.",options:{A:"medan",B:"sedan",C:"innan",D:"eftersom"},correct:"C"},
  {id:"s14",text:"– Jag måste ha lagt bilnyckeln någon annanstans ___ jag brukar.",options:{A:"som",B:"att",C:"om",D:"än"},correct:"D"},
  {id:"s15",text:"Karl-Anton har blivit utfattig ___ spela bort sina pengar på trav.",options:{A:"ifall",B:"som",C:"genom att",D:"trots att"},correct:"C"},
  {id:"s16",text:"Ulrika vill flytta hemifrån ___ hon inte trivs hemma hos sina föräldrar.",options:{A:"trots att",B:"därför att",C:"så att",D:"utan att"},correct:"B"},
  {id:"s17",text:"___ Kalle har erbjudits högre lön på sitt jobb har han sagt upp sig.",options:{A:"Eftersom",B:"Genom att",C:"Trots att",D:"Ifall"},correct:"C"},
  {id:"s18",text:"Resan till Moskva tog längre tid ___ vi hade trott.",options:{A:"att",B:"som",C:"än",D:"om"},correct:"C"},
  {id:"s19",text:"– Ta på dig vantar ___ du inte fryser om händerna!",options:{A:"eftersom",B:"så att",C:"innan",D:"utan att"},correct:"B"},
  {id:"s20",text:"I natt gick Anna och bar på sina tvillingar i flera timmar ___ de skulle sluta skrika.",options:{A:"för att",B:"trots att",C:"genom att",D:"innan"},correct:"A"},
  {id:"s21",text:"Elin tar vitamintabletter varje dag ___ hon ska få bättre motståndskraft.",options:{A:"som",B:"även om",C:"utan att",D:"för att"},correct:"D"},
  {id:"s22",text:"Pelle sov så hårt i morse ___ han inte hörde väckarklockan.",options:{A:"som",B:"att",C:"för att",D:"trots att"},correct:"B"},
  {id:"s23",text:"___ närmare diskot vi kom desto tydligare hörde vi musiken.",options:{A:"Så",B:"Som",C:"Ju",D:"När"},correct:"C"},
  {id:"s24",text:"– ___ du tycker att matten är lätt måste du öva lite före provet.",options:{A:"Om",B:"Även om",C:"När",D:"Eftersom"},correct:"B"},
  {id:"s25",text:"___ Olle inte hade hört av sig på länge ringde jag upp honom.",options:{A:"Innan",B:"Eftersom",C:"Därför att",D:"Som"},correct:"B"},
  {id:"s26",text:"Häromdagen köpte Janne en ny bil ___ hans fru visste om det.",options:{A:"därför att",B:"trots att",C:"utan att",D:"för att"},correct:"C"},
  {id:"s27",text:"___ jag var på semester passade grannen min katt.",options:{A:"Tills",B:"Medan",C:"Fastän",D:"Därför att"},correct:"B"},
  {id:"s28",text:"___ taxin inte kommer snart måste jag ringa taxibolaget igen.",options:{A:"När",B:"Eftersom",C:"Ifall",D:"Fastän"},correct:"C"},
  {id:"s29",text:"– Har du något emot ___ jag röker?",options:{A:"att",B:"när",C:"eftersom",D:"som"},correct:"A"},
  {id:"s30",text:"Jag ska ringa och fråga ___ jag möjligen kan få en annan tid hos doktorn.",options:{A:"att",B:"som",C:"om",D:"för att"},correct:"C"},
  {id:"s31",text:"Eva skaffade bil i våras ___ hon lättare skulle kunna ta sig till jobbet.",options:{A:"eftersom",B:"utan att",C:"för att",D:"trots att"},correct:"C"},
  {id:"s32",text:"I natt hostade min lilla pojke ___ han nästan tappade andan.",options:{A:"för att",B:"så att",C:"trots att",D:"genom att"},correct:"B"},
  {id:"s33",text:"Jag är lika lång ___ min mamma är.",options:{A:"som",B:"att",C:"än",D:"eftersom"},correct:"A"},
  {id:"s34",text:"Börje ska gifta sig med Karin ___ han inte älskar henne.",options:{A:"därför att",B:"utan att",C:"trots att",D:"så att"},correct:"C"},
  {id:"s35",text:"___ överklaga ett domslut kan man få sin sak prövad en gång till.",options:{A:"Trots att",B:"Genom att",C:"Så att",D:"Ifall"},correct:"B"},
  {id:"s36",text:"Sara blev inte politiskt medveten ___ hon började jobba.",options:{A:"förrän",B:"medan",C:"tills",D:"innan"},correct:"A"},
  {id:"s37",text:"___ jag minns rätt heter du Persson i efternamn, eller hur?",options:{A:"När",B:"Om",C:"Som",D:"Trots att"},correct:"B"},
  {id:"s38",text:"Doktor Ask sa ___ min far var på bättringsvägen.",options:{A:"om",B:"tills",C:"att",D:"som"},correct:"C"},
  {id:"s39",text:"Jag måste ta reda på ___ jag får kvarskatt eller inte.",options:{A:"att",B:"om",C:"när",D:"eftersom"},correct:"B"},
  {id:"s40",text:"Elsa har gift sig med herr Berg ___ hon ska få det bra ekonomiskt.",options:{A:"trots att",B:"för att",C:"innan",D:"som"},correct:"B"},
  {id:"s41",text:"Våra nyinflyttade grannar spikar och hamrar ___ vi inte får en lugn stund.",options:{A:"för att",B:"genom att",C:"utan att",D:"så att"},correct:"D"},
  {id:"s42",text:"Olof arbetar på samma arbetsplats ___ hans pappa gör.",options:{A:"än",B:"som",C:"eftersom",D:"trots att"},correct:"B"},
  {id:"s43",text:"___ filmen på TV slutar sent i kväll ska jag se den.",options:{A:"Därför att",B:"Även om",C:"Utan att",D:"Tills"},correct:"B"},
  {id:"s44",text:"För en tid sedan slutade Åke röka ___ han hade hostat väldigt länge.",options:{A:"därför att",B:"även om",C:"så att",D:"om"},correct:"A"},
  {id:"s45",text:"Albin kan inte somna ___ ta en whisky innan han lägger sig.",options:{A:"därför att",B:"utan att",C:"genom att",D:"så att"},correct:"B"},
  {id:"s46",text:"– ___ det har slutat regna ska jag ta en lång promenad.",options:{A:"Förrän",B:"Medan",C:"När",D:"Därför att"},correct:"C"},
  {id:"s47",text:"– Man måste läsa mycket ___ man vill ha bra betyg.",options:{A:"om",B:"att",C:"som",D:"så att"},correct:"A"},
  {id:"s48",text:"– Det är troligt ___ jag får jobbet som jag har sökt.",options:{A:"om",B:"som",C:"att",D:"när"},correct:"C"},
  {id:"s49",text:"Alla undrar ___ Petrus inte ska gifta sig med sin sambo någon gång.",options:{A:"att",B:"som",C:"om",D:"så att"},correct:"C"},
  {id:"s50",text:"Magnus ska lägga sig tidigt i kväll ___ han ska vara utvilad i morgon.",options:{A:"när",B:"för att",C:"fastän",D:"tills"},correct:"B"},
  {id:"s51",text:"– Se upp ___ du inte ramlar!",options:{A:"därför att",B:"genom att",C:"så att",D:"när"},correct:"C"},
  {id:"s52",text:"___ mer man motionerar desto bättre kondition får man.",options:{A:"När",B:"Eftersom",C:"Ju",D:"Fast"},correct:"C"},
  {id:"s53",text:"___ jag inte klarar provet i morgon ska jag gå ut och dansa på kvällen.",options:{A:"Trots att",B:"Även om",C:"Utan att",D:"Genom att"},correct:"B"},
  {id:"s54",text:"Jag ska ge Anita en bukett blommor ___ hon har hjälpt mig så mycket.",options:{A:"trots att",B:"därför att",C:"så att",D:"innan"},correct:"B"},
  {id:"s55",text:"– Alf har varit borta från jobbet en vecka ___ han har hört av sig.",options:{A:"eftersom",B:"utan att",C:"när",D:"trots att"},correct:"B"},
  {id:"s56",text:"Man kan inte äta vetebullar ___ man är glutenallergiker.",options:{A:"så att",B:"som",C:"om",D:"fast"},correct:"C"},
  {id:"s57",text:"Oskar tog en taxi till jobbet i morse ___ han inte skulle komma för sent.",options:{A:"när",B:"som om",C:"utan att",D:"för att"},correct:"D"},
  {id:"s58",text:"Bengt är så rädd för min hund ___ han aldrig vågar klappa den.",options:{A:"som",B:"att",C:"därför att",D:"trots att"},correct:"B"},
  {id:"s59",text:"På sitt nya jobb träffar Adam andra människor ___ han är van vid.",options:{A:"än",B:"att",C:"som",D:"om"},correct:"A"},
  {id:"s60",text:"– ___ herr Olsson är rik är han mycket snål.",options:{A:"Eftersom",B:"Därför att",C:"Trots att",D:"Utan att"},correct:"C"},
  {id:"s61",text:"___ herr Karlsson hade ljugit som vittne i rätten dömdes han för mened.",options:{A:"Därför att",B:"Eftersom",C:"Trots att",D:"Även om"},correct:"B"},
  {id:"s62",text:"Monica säger precis vad hon tycker och tänker ___ bry sig om vad andra tycker.",options:{A:"genom att",B:"utan att",C:"trots att",D:"för att"},correct:"B"},
  {id:"s63",text:"På midsommarafton är man ofta uppe ___ solen går upp.",options:{A:"även om",B:"tills",C:"förrän",D:"så att"},correct:"B"},
  {id:"s64",text:"– Jag är nästan säker på ___ alla kan det här nu.",options:{A:"som",B:"att",C:"om",D:"så att"},correct:"B"},
];

// ── FiF C Övn. 3 – Blandat (4 alternativ) ────────────────────────────────────
export const FIC_BLANDAT = [
  {id:"c01",text:"Det sägs att regeringen måste underlätta för företagen att skapa arbetstillfällen ___ sysselsättningen ska öka.",options:{A:"eftersom",B:"trots att",C:"genom att",D:"för att"},correct:"D"},
  {id:"c02",text:"I tingsrätten blev Sven Svensson dömd igår. Sanningen är att det inte var Sven Svensson som hade rånat en bank, ___ det var Per Persson.",options:{A:"fast",B:"men",C:"utan",D:"utan att"},correct:"C"},
  {id:"c03",text:"Man kan lindra värk ___ ta smärtstillande medicin.",options:{A:"så att",B:"för att",C:"genom att",D:"trots att"},correct:"C"},
  {id:"c04",text:"Regeringen backade i en viktig fråga ___ många hade protesterat mot dess beslut.",options:{A:"medan",B:"så länge som",C:"efter det att",D:"förrän"},correct:"C"},
  {id:"c05",text:"– ___ min ekonomi är ganska skral just nu måste jag försöka köpa julklappar till barnen.",options:{A:"Eftersom",B:"Även om",C:"Genom att",D:"Ifall"},correct:"B"},
  {id:"c06",text:"Tom kan inte ha kvar sin segelbåt ___ han jobbar extra.",options:{A:"genom att",B:"för att",C:"utan att",D:"så att"},correct:"C"},
  {id:"c07",text:"___ må bra måste man dels äta rätt, dels motionera mycket.",options:{A:"Att",B:"Efter att",C:"Så att",D:"För att"},correct:"D"},
  {id:"c08",text:"Erik gav med sig ___ han blivit övertygad om att han hade fel.",options:{A:"sedan",B:"medan",C:"ty",D:"även om"},correct:"A"},
  {id:"c09",text:"___ det gäller brott mot vapenlagen ser man en stor ökning i samhället.",options:{A:"När",B:"Medan",C:"Som",D:"Tills"},correct:"A"},
  {id:"c10",text:"Om dagisbarnen bär på bakterier bör de stanna hemma, ___ annars är det risk att de smittar varandra.",options:{A:"men",B:"och",C:"för",D:"eller"},correct:"C"},
  {id:"c11",text:"Reglerna på vår skola är utformade ___ alla kan följa dem.",options:{A:"därför att",B:"så att",C:"utan att",D:"genom att"},correct:"B"},
  {id:"c12",text:"___ en stor narkotikaliga hade avslöjats i våras var det många som gick under jorden.",options:{A:"Förrän",B:"Medan",C:"Efter det att",D:"Tills"},correct:"C"},
  {id:"c13",text:"Många bönder förlorar inkomst ___ deras djur av en eller annan anledning måste nödslaktas.",options:{A:"när",B:"som",C:"att",D:"utan"},correct:"A"},
  {id:"c14",text:"Juli är inte alltid en varm månad, ___ den kan minsann vara både kall och regnig.",options:{A:"fast",B:"utan",C:"så",D:"eller"},correct:"A"},
  {id:"c15",text:"Sverige blev medlem i EU ___ Finland hade blivit medlem.",options:{A:"medan",B:"och",C:"efter det att",D:"förrän"},correct:"C"},
  {id:"c16",text:"Vi vuxna lär barn hur de ska uppträda ___ vi föregår med gott exempel.",options:{A:"genom att",B:"för att",C:"så att",D:"efter det att"},correct:"A"},
  {id:"c17",text:"Medan jag satt och läste tidningen i söndags fick jag syn på en annons om en drömlägenhet, ___ jag kastade mig på telefonen.",options:{A:"men",B:"utan",C:"eller",D:"så"},correct:"D"},
  {id:"c18",text:"___ Karlsson har bestämt sig eller ej är fortfarande höljt i dunkel.",options:{A:"Såvida",B:"Huruvida",C:"Utan",D:"Eller"},correct:"B"},
  {id:"c19",text:"Teresa sitter och skriver på datorn ___ hon lyssnar på musik.",options:{A:"eftersom",B:"samtidigt som",C:"så ofta som",D:"just som"},correct:"B"},
  {id:"c20",text:"Ni ombedes återsända ansökan undertecknad ___ ni inte vill ta tillbaka den.",options:{A:"så att",B:"så",C:"såvida",D:"när"},correct:"C"},
  {id:"c21",text:"– Du måste ta den här medicinen ___ du vill ___ inte.",options:{A:"såväl...som",B:"varken...eller",C:"antingen...eller",D:"både...och"},correct:"C"},
  {id:"c22",text:"Peder känner sig ofta väldigt osäker ___ andra alltid uppfattar honom som en mycket självsäker person.",options:{A:"genom att",B:"samtidigt som",C:"utan att",D:"sedan"},correct:"B"},
  {id:"c23",text:"___ Ester ___ hennes man jobbar idag. Båda ligger hemma i influensa.",options:{A:"Såväl...som",B:"Antingen...eller",C:"Varken...eller",D:"Både...och"},correct:"C"},
  {id:"c24",text:"Ibland demonstrerar och protesterar folk ___ myndigheterna ska ändra vissa beslut.",options:{A:"genom att",B:"sedan",C:"tills",D:"för att"},correct:"D"},
  {id:"c25",text:"___ Fritiof hade fått förhinder kunde han inte gå på mötet igår.",options:{A:"Därför att",B:"Som",C:"Ty",D:"Emedan"},correct:"D"},
  {id:"c26",text:"När man har kikhosta hostar man ___ man kiknar.",options:{A:"när",B:"för",C:"så att",D:"genom att"},correct:"C"},
  {id:"c27",text:"___ tvättmaskinen är sönder måste fru Ek tvätta det nödvändigaste för hand.",options:{A:"Till dess att",B:"Under det att",C:"Eftersom",D:"Innan"},correct:"C"},
  {id:"c28",text:"I natt satt Karin uppe och väntade. ___ timmarna gick blev hon mer och mer nervös.",options:{A:"Därför att",B:"Allt eftersom",C:"Alltsedan",D:"Alldenstund"},correct:"B"},
  {id:"c29",text:"– ___ du bara hör av dig då och då så kan jag vara lugn.",options:{A:"Utan att",B:"Trots att",C:"Så att",D:"Om"},correct:"D"},
  {id:"c30",text:"Vissa personer får biverkningar av en del mediciner ___ andra tål dessa läkemedel.",options:{A:"eftersom",B:"eller",C:"under det att",D:"huruvida"},correct:"C"},
  {id:"c31",text:"Visst har vi höga skatter i Sverige, ___ så får vi också ganska mycket för pengarna.",options:{A:"och",B:"eller",C:"utan",D:"men"},correct:"D"},
  {id:"c32",text:"– ___ fler timmar man sover desto tröttare blir man, påstår en del.",options:{A:"Ju",B:"Som",C:"Än",D:"Att"},correct:"A"},
  {id:"c33",text:"I natt satt Ulrik uppe och jobbade ___ hans fru vaknade och undrade vad som stod på.",options:{A:"efter det att",B:"medan",C:"till dess att",D:"allteftersom"},correct:"C"},
  {id:"c34",text:"Tobias kunde inte köpa sin drömvilla ___ banken inte ville bevilja lånet.",options:{A:"alltsedan",B:"emedan",C:"så att",D:"huruvida"},correct:"B"},
  {id:"c35",text:"Kakan som Olle bakade blev misslyckad eftersom han inte gjorde så ___ hans mor hade sagt.",options:{A:"än",B:"att",C:"som",D:"som om"},correct:"C"},
  {id:"c36",text:"Om man får influensa med hög feber bör man ta febernedsättande medicin ___ febern går ner.",options:{A:"för att",B:"så att",C:"därför att",D:"genom att"},correct:"B"},
  {id:"c37",text:"Det är ett känt faktum ___ många våldsmän inte har förmåga att känna empati.",options:{A:"att",B:"så",C:"som",D:"eftersom"},correct:"A"},
  {id:"c38",text:"Många elever låtsas ___ de förstår trots att de egentligen inte gör det.",options:{A:"om",B:"att",C:"huruvida",D:"såvida"},correct:"B"},
  {id:"c39",text:"Ulf har aldrig gillat tecknade serier ___ som barn ___ som vuxen.",options:{A:"såväl...som",B:"antingen...eller",C:"vare sig...eller",D:"både...och"},correct:"C"},
  {id:"c40",text:"Förvisso hade Anita inte trott att hon skulle klara provet, ___ att det skulle gå så dåligt hade hon inte den blekaste aning om.",options:{A:"och",B:"eller",C:"men",D:"utan"},correct:"C"},
  {id:"c41",text:"– Tänk om jag kunde hitta en sådan julgran ___ vi hade i fjol.",options:{A:"som",B:"att",C:"än",D:"så"},correct:"A"},
  {id:"c42",text:"Kaj trodde inte att han kunde bli kär ___ han hade träffat Ana.",options:{A:"medan",B:"när",C:"förrän",D:"eftersom"},correct:"C"},
  {id:"c43",text:"– Jag måste genast få tala med dig. Kom hit ___ du kan!",options:{A:"just som",B:"samtidigt som",C:"så snart som",D:"så ofta som"},correct:"C"},
  {id:"c44",text:"___ klockan slog tolv på nyårsnatten fylldes himlen av raketer.",options:{A:"Utan att",B:"Även om",C:"Just som",D:"Så ofta som"},correct:"C"},
  {id:"c45",text:"– Jag tror att jag ska köpa likadana stövlar till Mari ___ jag köpte till Eva igår.",options:{A:"när",B:"att",C:"medan",D:"som"},correct:"D"},
  {id:"c46",text:"Fru Glans åker till Köpenhamn och handlar ___ hon har tillfälle.",options:{A:"så ofta som",B:"just som",C:"såsom",D:"liksom"},correct:"A"},
  {id:"c47",text:"Många svenskar åker till södra Europa på semester ___ många andra nordbor.",options:{A:"liksom",B:"såsom",C:"eftersom",D:"just som"},correct:"A"},
  {id:"c48",text:"– Du måste vila efter svensexan ___ du blir pigg till bröllopet.",options:{A:"för att",B:"därför att",C:"så att",D:"genom att"},correct:"C"},
  {id:"c49",text:"Man bör studera mycket grammatik, ___ man får inte glömma att tillämpa dessa kunskaper i dagliga livet.",options:{A:"för",B:"men",C:"utan",D:"så"},correct:"B"},
];

export const BUILT_IN_TESTS = [
  {
    id:"fib-konj",
    title:"FiF B – Konjunktioner (övn. 2)",
    category:"Konjunktioner",
    source:"FiF B",
    locked:true,
    questions:FIB_KONJ
  },
  {
    id:"fib-subj",
    title:"FiF B – Subjunktioner (övn. 5)",
    category:"Subjunktioner",
    source:"FiF B",
    locked:true,
    questions:FIB_SUBJ
  },
  {
    id:"fic-blandat",
    title:"FiF C – Konjunktioner & subjunktioner (övn. 3)",
    category:"Blandat",
    source:"FiF C",
    locked:true,
    questions:FIC_BLANDAT
  },
];

export const CATEGORIES = [
  "Konjunktioner",
  "Subjunktioner – orsak",
  "Subjunktioner – tid",
  "Subjunktioner – villkor",
  "Subjunktioner – mål/avsikt",
  "Subjunktioner – sätt/metod",
  "Subjunktioner – jämförande",
  "Subjunktioner – konsekvens",
  "Subjunktioner – motsats/motsättning",
  "Subjunktioner – allmänt underordnande (att)",
  "Blandat",
];
